"""Added unique param in username field in Admin model

Revision ID: d8ba1dd6b82c
Revises: d4f9079b7287
Create Date: 2025-12-23 12:37:30.834072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8ba1dd6b82c'
down_revision: Union[str, Sequence[str], None] = 'd4f9079b7287'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_admin_username'), table_name='admin')
    op.create_index(op.f('ix_admin_username'), 'admin', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_admin_username'), table_name='admin')
    op.create_index(op.f('ix_admin_username'), 'admin', ['username'], unique=False)
    # ### end Alembic commands ###
