"""add invoice field in User model

Revision ID: 0265e20d6159
Revises: 5fe308b09770
Create Date: 2025-12-23 11:52:15.554471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0265e20d6159'
down_revision: Union[str, Sequence[str], None] = '5fe308b09770'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('invoice', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'invoice')
    # ### end Alembic commands ###
