"""added passport url in user model

Revision ID: bbd1cdb955a8
Revises: dfa19f0c75af
Create Date: 2025-12-05 10:46:18.836936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbd1cdb955a8'
down_revision: Union[str, Sequence[str], None] = 'dfa19f0c75af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('passport_url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'passport_url')
    # ### end Alembic commands ###
