"""fix contract model

Revision ID: bec8c14c497b
Revises: c079f7f49910
Create Date: 2025-12-29 10:55:35.014456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bec8c14c497b'
down_revision: Union[str, Sequence[str], None] = 'c079f7f49910'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contract', 'transport_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contract', 'transport_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
