"""create new model and add new fields in User model

Revision ID: c079f7f49910
Revises: a47491a8214e
Create Date: 2025-12-29 10:53:34.487071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c079f7f49910'
down_revision: Union[str, Sequence[str], None] = 'a47491a8214e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('residencepermit',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('front_side', sa.Integer(), nullable=False),
    sa.Column('back_side', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['back_side'], ['file.id'], ),
    sa.ForeignKeyConstraint(['front_side'], ['file.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('contract', 'transport_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('user', sa.Column('telegram', sa.String(length=255), nullable=True))
    op.add_column('user', sa.Column('city', sa.String(length=255), nullable=True))
    op.add_column('user', sa.Column('address', sa.String(length=528), nullable=True))
    op.add_column('user', sa.Column('stay_type', sa.String(length=50), nullable=True))
    op.add_column('user', sa.Column('insurance_file', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'file', ['insurance_file'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'insurance_file')
    op.drop_column('user', 'stay_type')
    op.drop_column('user', 'address')
    op.drop_column('user', 'city')
    op.drop_column('user', 'telegram')
    op.alter_column('contract', 'transport_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_table('residencepermit')
    # ### end Alembic commands ###
