"""add transport model

Revision ID: c4f9b02db5ad
Revises: 3c761e4dfbfa
Create Date: 2025-12-05 10:37:15.456017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4f9b02db5ad'
down_revision: Union[str, Sequence[str], None] = '3c761e4dfbfa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transport',
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('manufacturer', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=255), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('number', sa.String(length=20), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transport_manufacturer'), 'transport', ['manufacturer'], unique=False)
    op.create_index(op.f('ix_transport_model'), 'transport', ['model'], unique=False)
    op.create_index(op.f('ix_transport_type'), 'transport', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transport_type'), table_name='transport')
    op.drop_index(op.f('ix_transport_model'), table_name='transport')
    op.drop_index(op.f('ix_transport_manufacturer'), table_name='transport')
    op.drop_table('transport')
    # ### end Alembic commands ###
