"""Deleted contract_url and add contract_file in Contract model

Revision ID: a47491a8214e
Revises: 3d51238d437d
Create Date: 2025-12-23 13:51:50.501459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a47491a8214e'
down_revision: Union[str, Sequence[str], None] = '3d51238d437d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contract', sa.Column('contract_file', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'contract', 'file', ['contract_file'], ['id'])
    op.drop_column('contract', 'contract_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contract', sa.Column('contract_url', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'contract', type_='foreignkey')
    op.drop_column('contract', 'contract_file')
    # ### end Alembic commands ###
