"""Added visa field in user model

Revision ID: 43882d03149f
Revises: bec8c14c497b
Create Date: 2025-12-29 12:15:39.894428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43882d03149f'
down_revision: Union[str, Sequence[str], None] = 'bec8c14c497b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('visa_file', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'file', ['visa_file'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'visa_file')
    # ### end Alembic commands ###
