"""Deleted passport_url and add passport_file field in User model

Revision ID: 3d51238d437d
Revises: d8ba1dd6b82c
Create Date: 2025-12-23 13:24:58.289099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d51238d437d'
down_revision: Union[str, Sequence[str], None] = 'd8ba1dd6b82c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('passport_file', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'file', ['passport_file'], ['id'])
    op.drop_column('user', 'passport_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('passport_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'passport_file')
    # ### end Alembic commands ###
