"""add defaul func now in contract model

Revision ID: 4eb88c119a8f
Revises: 4e21b1a4b29d
Create Date: 2025-12-07 10:05:07.516763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4eb88c119a8f'
down_revision: Union[str, Sequence[str], None] = '4e21b1a4b29d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
