"""Added product model

Revision ID: 094ecb44fd3a
Revises: 1119ecb61d1a
Create Date: 2026-02-20 09:43:42.226356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '094ecb44fd3a'
down_revision: Union[str, Sequence[str], None] = '1119ecb61d1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('name', sa.String(), nullable=False, max_length=120),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=False, max_length=500),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False, max_length=20),
    sa.Column('status', sa.String(), nullable=False, max_length=20),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contract.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product')
    # ### end Alembic commands ###
