"""added consent in user model

Revision ID: 7e00b8653ca0
Revises: 34fd8cb3dc11
Create Date: 2026-03-26 10:54:39.720180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e00b8653ca0'
down_revision: Union[str, Sequence[str], None] = '34fd8cb3dc11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('consent', sa.Boolean(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'consent')
    # ### end Alembic commands ###
