"""delete visa_file

Revision ID: 0d9885055b52
Revises: f8e89e7be9bd
Create Date: 2026-02-14 14:27:29.858087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d9885055b52'
down_revision: Union[str, Sequence[str], None] = 'f8e89e7be9bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('user_visa_file_fkey'), 'user', type_='foreignkey')
    op.drop_column('user', 'visa_file')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('visa_file', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('user_visa_file_fkey'), 'user', 'file', ['visa_file'], ['id'])
    # ### end Alembic commands ###
