"""add how_found_it

Revision ID: 8a49cbcff8c5
Revises: 137f7dbd1f55
Create Date: 2026-02-25 09:31:16.916966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a49cbcff8c5'
down_revision: Union[str, Sequence[str], None] = '137f7dbd1f55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('how_found_it', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'how_found_it')
    # ### end Alembic commands ###
