"""added rental price in Transport model

Revision ID: 137f7dbd1f55
Revises: 5d0f99b6e496
Create Date: 2026-02-21 08:57:43.003086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '137f7dbd1f55'
down_revision: Union[str, Sequence[str], None] = '5d0f99b6e496'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transport', sa.Column('rental_price', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transport', 'rental_price')
    # ### end Alembic commands ###
