"""added message field in transport model

Revision ID: f8e89e7be9bd
Revises: 005f8f675ca1
Create Date: 2026-02-13 15:22:29.996129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8e89e7be9bd'
down_revision: Union[str, Sequence[str], None] = '005f8f675ca1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transport', sa.Column('message', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transport', 'message')
    # ### end Alembic commands ###
