"""Added citizenship in User model

Revision ID: a103b8ac4284
Revises: 7e00b8653ca0
Create Date: 2026-03-26 11:00:59.557938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a103b8ac4284'
down_revision: Union[str, Sequence[str], None] = '7e00b8653ca0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('citizenship', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'citizenship')
    # ### end Alembic commands ###
