"""delete unique constraint in Document Model

Revision ID: 1bfdd1129a82
Revises: 660fe8162b60
Create Date: 2026-03-28 11:42:36.539674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1bfdd1129a82'
down_revision: Union[str, Sequence[str], None] = '660fe8162b60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('document_file_id_key'), 'document', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('document_file_id_key'), 'document', ['file_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
