"""create-db

Revision ID: 4d7c3e2269b6
Revises: 
Create Date: 2026-01-19 16:32:07.048880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d7c3e2269b6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_username'), 'admin', ['username'], unique=True)
    op.create_table('file',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('link', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transport',
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('manufacturer', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=255), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('number', sa.String(length=20), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transport_manufacturer'), 'transport', ['manufacturer'], unique=False)
    op.create_index(op.f('ix_transport_model'), 'transport', ['model'], unique=False)
    op.create_index(op.f('ix_transport_type'), 'transport', ['type'], unique=False)
    op.create_table('user',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=False),
    sa.Column('telegram', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=255), nullable=True),
    sa.Column('address', sa.String(length=528), nullable=True),
    sa.Column('stay_type', sa.String(length=50), nullable=True),
    sa.Column('work_in', sa.String(length=50), nullable=False),
    sa.Column('passport_file', sa.Integer(), nullable=True),
    sa.Column('insurance_file', sa.Integer(), nullable=True),
    sa.Column('visa_file', sa.Integer(), nullable=True),
    sa.Column('invoice', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['insurance_file'], ['file.id'], ),
    sa.ForeignKeyConstraint(['passport_file'], ['file.id'], ),
    sa.ForeignKeyConstraint(['visa_file'], ['file.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_user_name'), 'user', ['name'], unique=False)
    op.create_index(op.f('ix_user_phone'), 'user', ['phone'], unique=False)
    op.create_index(op.f('ix_user_work_in'), 'user', ['work_in'], unique=False)
    op.create_table('contract',
    sa.Column('contract_file', sa.Integer(), nullable=True),
    sa.Column('transport_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date_of_signing', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['contract_file'], ['file.id'], ),
    sa.ForeignKeyConstraint(['transport_id'], ['transport.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('residencepermit',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('front_side', sa.Integer(), nullable=False),
    sa.Column('back_side', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['back_side'], ['file.id'], ),
    sa.ForeignKeyConstraint(['front_side'], ['file.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('residencepermit')
    op.drop_table('contract')
    op.drop_index(op.f('ix_user_work_in'), table_name='user')
    op.drop_index(op.f('ix_user_phone'), table_name='user')
    op.drop_index(op.f('ix_user_name'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_transport_type'), table_name='transport')
    op.drop_index(op.f('ix_transport_model'), table_name='transport')
    op.drop_index(op.f('ix_transport_manufacturer'), table_name='transport')
    op.drop_table('transport')
    op.drop_table('file')
    op.drop_index(op.f('ix_admin_username'), table_name='admin')
    op.drop_table('admin')
    # ### end Alembic commands ###
