"""deleted stay_type

Revision ID: 660fe8162b60
Revises: a103b8ac4284
Create Date: 2026-03-26 11:04:40.519607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '660fe8162b60'
down_revision: Union[str, Sequence[str], None] = 'a103b8ac4284'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'stay_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('stay_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
