"""delete file-field in User model

Revision ID: 437252d3fc81
Revises: 4d7c3e2269b6
Create Date: 2026-02-07 08:07:48.417909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '437252d3fc81'
down_revision: Union[str, Sequence[str], None] = '4d7c3e2269b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('user_passport_file_fkey'), 'user', type_='foreignkey')
    op.drop_constraint(op.f('user_insurance_file_fkey'), 'user', type_='foreignkey')
    op.drop_column('user', 'passport_file')
    op.drop_column('user', 'insurance_file')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('insurance_file', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('passport_file', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('user_insurance_file_fkey'), 'user', 'file', ['insurance_file'], ['id'])
    op.create_foreign_key(op.f('user_passport_file_fkey'), 'user', 'file', ['passport_file'], ['id'])
    # ### end Alembic commands ###
