"""added whatsapp in User model

Revision ID: 1119ecb61d1a
Revises: fabb632f722e
Create Date: 2026-02-18 09:11:42.889236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1119ecb61d1a'
down_revision: Union[str, Sequence[str], None] = 'fabb632f722e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('whatsapp', sa.String(length=15), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'whatsapp')
    # ### end Alembic commands ###
