"""delete residence permit

Revision ID: 005f8f675ca1
Revises: 437252d3fc81
Create Date: 2026-02-07 08:48:21.174290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '005f8f675ca1'
down_revision: Union[str, Sequence[str], None] = '437252d3fc81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['file.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_id')
    )
    op.drop_table('residencepermit')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('residencepermit',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('front_side', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('back_side', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['back_side'], ['file.id'], name=op.f('residencepermit_back_side_fkey')),
    sa.ForeignKeyConstraint(['front_side'], ['file.id'], name=op.f('residencepermit_front_side_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('residencepermit_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('residencepermit_pkey'))
    )
    op.drop_table('document')
    # ### end Alembic commands ###
